// find:
// replace:

var fastMoves =
[
	{
		"name": "Acid",
		"type": "Poison",
		"pvpDamage": 6,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 9,
		"pveEnergy": 8,
		"pveCooldown": 0.8
	},
	{
		"name": "Air Slash",
		"type": "Flying",
		"pvpDamage": 9,
		"pvpEnergy": 9,
		"pvpTurns": 3,
		"pveDamage": 14,
		"pveEnergy": 10,
		"pveCooldown": 1.2
	},
	{
		"name": "Astonish",
		"type": "Ghost",
		"pvpDamage": 5,
		"pvpEnergy": 9,
		"pvpTurns": 3,
		"pveDamage": 8,
		"pveEnergy": 14,
		"pveCooldown": 1.1
	},
	{
		"name": "Bite",
		"type": "Dark",
		"pvpDamage": 4,
		"pvpEnergy": 2,
		"pvpTurns": 1,
		"pveDamage": 6,
		"pveEnergy": 4,
		"pveCooldown": 0.5
	},
	{
		"name": "Bubble",
		"type": "Water",
		"pvpDamage": 8,
		"pvpEnergy": 11,
		"pvpTurns": 3,
		"pveDamage": 12,
		"pveEnergy": 14,
		"pveCooldown": 1.2
	},
	{
		"name": "Bug Bite",
		"type": "Bug",
		"pvpDamage": 3,
		"pvpEnergy": 3,
		"pvpTurns": 1,
		"pveDamage": 5,
		"pveEnergy": 6,
		"pveCooldown": 0.5
	},
	{
		"name": "Bullet Punch",
		"type": "Steel",
		"pvpDamage": 6,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 9,
		"pveEnergy": 10,
		"pveCooldown": 0.9
	},
	{
		"name": "Bullet Seed",
		"type": "Grass",
		"pvpDamage": 5,
		"pvpEnergy": 13,
		"pvpTurns": 3,
		"pveDamage": 8,
		"pveEnergy": 14,
		"pveCooldown": 1.1
	},
	{
		"name": "Bullet Seed (Community Day)",
		"type": "Grass",
		"pvpDamage": 5,
		"pvpEnergy": 13,
		"pvpTurns": 3,
		"pveDamage": 8,
		"pveEnergy": 14,
		"pveCooldown": 1.1
	},
	{
		"name": "Charge Beam",
		"type": "Electric",
		"pvpDamage": 5,
		"pvpEnergy": 11,
		"pvpTurns": 3,
		"pveDamage": 8,
		"pveEnergy": 15,
		"pveCooldown": 1.1
	},
	{
		"name": "Charm",
		"type": "Fairy",
		"pvpDamage": 16,
		"pvpEnergy": 6,
		"pvpTurns": 3,
		"pveDamage": 20,
		"pveEnergy": 11,
		"pveCooldown": 1.5
	},
	{
		"name": "Confusion",
		"type": "Psychic",
		"pvpDamage": 16,
		"pvpEnergy": 12,
		"pvpTurns": 4,
		"pveDamage": 20,
		"pveEnergy": 15,
		"pveCooldown": 1.6
	},
	{
		"name": "Counter",
		"type": "Fighting",
		"pvpDamage": 8,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 12,
		"pveEnergy": 8,
		"pveCooldown": 0.9
	},
	{
		"name": "Cut",
		"type": "Normal",
		"pvpDamage": 3,
		"pvpEnergy": 2,
		"pvpTurns": 1,
		"pveDamage": 5,
		"pveEnergy": 5,
		"pveCooldown": 0.5
	},
	{
		"name": "Dragon Breath",
		"type": "Dragon",
		"pvpDamage": 4,
		"pvpEnergy": 3,
		"pvpTurns": 1,
		"pveDamage": 6,
		"pveEnergy": 4,
		"pveCooldown": 0.5
	},
	{
		"name": "Dragon Tail",
		"type": "Dragon",
		"pvpDamage": 9,
		"pvpEnergy": 10,
		"pvpTurns": 3,
		"pveDamage": 15,
		"pveEnergy": 9,
		"pveCooldown": 1.1
	},
	{
		"name": "Ember",
		"type": "Fire",
		"pvpDamage": 6,
		"pvpEnergy": 6,
		"pvpTurns": 2,
		"pveDamage": 10,
		"pveEnergy": 10,
		"pveCooldown": 1
	},
	{
		"name": "Extrasensory",
		"type": "Psychic",
		"pvpDamage": 8,
		"pvpEnergy": 10,
		"pvpTurns": 3,
		"pveDamage": 12,
		"pveEnergy": 12,
		"pveCooldown": 1.1
	},
	{
		"name": "Feint Attack",
		"type": "Dark",
		"pvpDamage": 6,
		"pvpEnergy": 6,
		"pvpTurns": 2,
		"pveDamage": 10,
		"pveEnergy": 9,
		"pveCooldown": 0.9
	},
	{
		"name": "Fire Fang",
		"type": "Fire",
		"pvpDamage": 8,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 12,
		"pveEnergy": 8,
		"pveCooldown": 0.9
	},
	{
		"name": "Fire Spin",
		"type": "Fire",
		"pvpDamage": 9,
		"pvpEnergy": 10,
		"pvpTurns": 3,
		"pveDamage": 14,
		"pveEnergy": 10,
		"pveCooldown": 1.1
	},
	{
		"name": "Frost Breath",
		"type": "Ice",
		"pvpDamage": 7,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 10,
		"pveEnergy": 8,
		"pveCooldown": 0.9
	},
	{
		"name": "Fury Cutter",
		"type": "Bug",
		"pvpDamage": 2,
		"pvpEnergy": 4,
		"pvpTurns": 1,
		"pveDamage": 3,
		"pveEnergy": 6,
		"pveCooldown": 0.4
	},
	{
		"name": "Hex",
		"type": "Ghost",
		"pvpDamage": 6,
		"pvpEnergy": 11,
		"pvpTurns": 3,
		"pveDamage": 10,
		"pveEnergy": 15,
		"pveCooldown": 1.2
	},
	{
		"name": "Hidden Power",
		"type": "Normal",
		"pvpDamage": 9,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 15,
		"pveEnergy": 15,
		"pveCooldown": 1.5
	},
	{
		"name": "Ice Fang",
		"type": "Ice",
		"pvpDamage": 8,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 12,
		"pveEnergy": 20,
		"pveCooldown": 1.5
	},
	{
		"name": "Ice Shard",
		"type": "Ice",
		"pvpDamage": 9,
		"pvpEnergy": 10,
		"pvpTurns": 3,
		"pveDamage": 12,
		"pveEnergy": 12,
		"pveCooldown": 1.2
	},
	{
		"name": "Infestation",
		"type": "Bug",
		"pvpDamage": 6,
		"pvpEnergy": 11,
		"pvpTurns": 3,
		"pveDamage": 10,
		"pveEnergy": 14,
		"pveCooldown": 1.1
	},
	{
		"name": "Iron Tail",
		"type": "Steel",
		"pvpDamage": 9,
		"pvpEnergy": 6,
		"pvpTurns": 3,
		"pveDamage": 15,
		"pveEnergy": 7,
		"pveCooldown": 1.1
	},
	{
		"name": "Karate Chop",
		"type": "Fighting",
		"pvpDamage": 5,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 8,
		"pveEnergy": 10,
		"pveCooldown": 0.8
	},
	{
		"name": "Lick",
		"type": "Ghost",
		"pvpDamage": 3,
		"pvpEnergy": 3,
		"pvpTurns": 1,
		"pveDamage": 5,
		"pveEnergy": 6,
		"pveCooldown": 0.5
	},
	{
		"name": "Lock On",
		"type": "Normal",
		"pvpDamage": 1,
		"pvpEnergy": 5,
		"pvpTurns": 1,
		"pveDamage": 1,
		"pveEnergy": 6,
		"pveCooldown": 0.3
	},
	{
		"name": "Low Kick",
		"type": "Fighting",
		"pvpDamage": 4,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 6,
		"pveEnergy": 6,
		"pveCooldown": 0.6
	},
	{
		"name": "Metal Claw",
		"type": "Steel",
		"pvpDamage": 5,
		"pvpEnergy": 6,
		"pvpTurns": 2,
		"pveDamage": 8,
		"pveEnergy": 7,
		"pveCooldown": 0.7
	},
	{
		"name": "Mud Shot",
		"type": "Ground",
		"pvpDamage": 3,
		"pvpEnergy": 9,
		"pvpTurns": 2,
		"pveDamage": 5,
		"pveEnergy": 7,
		"pveCooldown": 0.6
	},
	{
		"name": "Mud Slap",
		"type": "Ground",
		"pvpDamage": 11,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 18,
		"pveEnergy": 12,
		"pveCooldown": 1.4
	},
	{
		"name": "Peck",
		"type": "Flying",
		"pvpDamage": 6,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 10,
		"pveEnergy": 10,
		"pveCooldown": 1
	},
	{
		"name": "Poison Jab",
		"type": "Poison",
		"pvpDamage": 6,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 10,
		"pveEnergy": 7,
		"pveCooldown": 0.8
	},
	{
		"name": "Poison Sting",
		"type": "Poison",
		"pvpDamage": 3,
		"pvpEnergy": 6,
		"pvpTurns": 2,
		"pveDamage": 5,
		"pveEnergy": 7,
		"pveCooldown": 0.6
	},
	{
		"name": "Pound",
		"type": "Normal",
		"pvpDamage": 5,
		"pvpEnergy": 4,
		"pvpTurns": 2,
		"pveDamage": 7,
		"pveEnergy": 6,
		"pveCooldown": 0.6
	},
	{
		"name": "Powder Snow",
		"type": "Ice",
		"pvpDamage": 4,
		"pvpEnergy": 8,
		"pvpTurns": 2,
		"pveDamage": 6,
		"pveEnergy": 15,
		"pveCooldown": 1
	},
	{
		"name": "Present",
		"type": "Normal",
		"pvpDamage": 3,
		"pvpEnergy": 12,
		"pvpTurns": 3,
		"pveDamage": 5,
		"pveEnergy": 20,
		"pveCooldown": 1.3
	},
	{
		"name": "Psycho Cut",
		"type": "Psychic",
		"pvpDamage": 3,
		"pvpEnergy": 9,
		"pvpTurns": 2,
		"pveDamage": 5,
		"pveEnergy": 8,
		"pveCooldown": 0.6
	},
	{
		"name": "Quick Attack",
		"type": "Normal",
		"pvpDamage": 5,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 8,
		"pveEnergy": 10,
		"pveCooldown": 0.8
	},
	{
		"name": "Razor Leaf",
		"type": "Grass",
		"pvpDamage": 11,
		"pvpEnergy": 4,
		"pvpTurns": 2,
		"pveDamage": 13,
		"pveEnergy": 7,
		"pveCooldown": 1
	},
	{
		"name": "Rock Smash",
		"type": "Fighting",
		"pvpDamage": 9,
		"pvpEnergy": 7,
		"pvpTurns": 3,
		"pveDamage": 15,
		"pveEnergy": 10,
		"pveCooldown": 1.3
	},
	{
		"name": "Rock Throw",
		"type": "Rock",
		"pvpDamage": 8,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 12,
		"pveEnergy": 7,
		"pveCooldown": 0.9
	},
	{
		"name": "Scratch",
		"type": "Normal",
		"pvpDamage": 4,
		"pvpEnergy": 2,
		"pvpTurns": 1,
		"pveDamage": 6,
		"pveEnergy": 4,
		"pveCooldown": 0.5
	},
	{
		"name": "Shadow Claw",
		"type": "Ghost",
		"pvpDamage": 6,
		"pvpEnergy": 8,
		"pvpTurns": 2,
		"pveDamage": 9,
		"pveEnergy": 6,
		"pveCooldown": 0.7
	},
	{
		"name": "Smack Down",
		"type": "Rock",
		"pvpDamage": 12,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 16,
		"pveEnergy": 8,
		"pveCooldown": 1.2
	},
	{
		"name": "Smack Down (Community Day)",
		"type": "Rock",
		"pvpDamage": 12,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 16,
		"pveEnergy": 8,
		"pveCooldown": 1.2
	},
	{
		"name": "Snarl",
		"type": "Dark",
		"pvpDamage": 5,
		"pvpEnergy": 13,
		"pvpTurns": 3,
		"pveDamage": 12,
		"pveEnergy": 14,
		"pveCooldown": 1.1
	},
	{
		"name": "Spark",
		"type": "Electric",
		"pvpDamage": 4,
		"pvpEnergy": 8,
		"pvpTurns": 2,
		"pveDamage": 6,
		"pveEnergy": 9,
		"pveCooldown": 0.7
	},
	{
		"name": "Splash",
		"type": "Water",
		"pvpDamage": 0,
		"pvpEnergy": 12,
		"pvpTurns": 4,
		"pveDamage": 0,
		"pveEnergy": 20,
		"pveCooldown": 1.73
	},
	{
		"name": "Steel Wing",
		"type": "Steel",
		"pvpDamage": 7,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 11,
		"pveEnergy": 6,
		"pveCooldown": 0.8
	},
	{
		"name": "Struggle Bug",
		"type": "Bug",
		"pvpDamage": 9,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 15,
		"pveEnergy": 15,
		"pveCooldown": 1.5
	},
	{
		"name": "Sucker Punch",
		"type": "Dark",
		"pvpDamage": 5,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 7,
		"pveEnergy": 8,
		"pveCooldown": 0.7
	},
	{
		"name": "Tackle",
		"type": "Normal",
		"pvpDamage": 3,
		"pvpEnergy": 2,
		"pvpTurns": 1,
		"pveDamage": 5,
		"pveEnergy": 5,
		"pveCooldown": 0.5
	},
	{
		"name": "Take Down",
		"type": "Normal",
		"pvpDamage": 5,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 8,
		"pveEnergy": 10,
		"pveCooldown": 1.2
	},
	{
		"name": "Thunder Fang",
		"type": "Electric",
		"pvpDamage": 8,
		"pvpEnergy": 5,
		"pvpTurns": 2,
		"pveDamage": 12,
		"pveEnergy": 16,
		"pveCooldown": 1.2
	},
	{
		"name": "Thunder Shock",
		"type": "Electric",
		"pvpDamage": 3,
		"pvpEnergy": 9,
		"pvpTurns": 2,
		"pveDamage": 5,
		"pveEnergy": 8,
		"pveCooldown": 0.6
	},
	{
		"name": "Transform",
		"type": "Normal",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpTurns": 6,
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 2.23
	},
	{
		"name": "Vine Whip",
		"type": "Grass",
		"pvpDamage": 5,
		"pvpEnergy": 8,
		"pvpTurns": 2,
		"pveDamage": 7,
		"pveEnergy": 6,
		"pveCooldown": 0.6
	},
	{
		"name": "Volt Switch",
		"type": "Electric",
		"pvpDamage": 12,
		"pvpEnergy": 16,
		"pvpTurns": 4,
		"pveDamage": 14,
		"pveEnergy": 21,
		"pveCooldown": 1.6
	},
	{
		"name": "Water Gun",
		"type": "Water",
		"pvpDamage": 3,
		"pvpEnergy": 3,
		"pvpTurns": 1,
		"pveDamage": 5,
		"pveEnergy": 5,
		"pveCooldown": 0.5
	},
	{
		"name": "Waterfall",
		"type": "Water",
		"pvpDamage": 12,
		"pvpEnergy": 8,
		"pvpTurns": 3,
		"pveDamage": 16,
		"pveEnergy": 8,
		"pveCooldown": 1.2
	},
	{
		"name": "Wing Attack",
		"type": "Flying",
		"pvpDamage": 5,
		"pvpEnergy": 7,
		"pvpTurns": 2,
		"pveDamage": 8,
		"pveEnergy": 9,
		"pveCooldown": 0.8
	},
	{
		"name": "Yawn",
		"type": "Normal",
		"pvpDamage": 0,
		"pvpEnergy": 12,
		"pvpTurns": 4,
		"pveDamage": 0,
		"pveEnergy": 15,
		"pveCooldown": 1.7
	},
	{
		"name": "Zen Headbutt",
		"type": "Psychic",
		"pvpDamage": 8,
		"pvpEnergy": 6,
		"pvpTurns": 3,
		"pveDamage": 12,
		"pveEnergy": 10,
		"pveCooldown": 1.1
	}
];

var fastMovesMap = {};
fastMoves.forEach(
    function(move) {
        let name = move.name;
        fastMovesMap[name] = move;
    }
);

// find:
// replace:

var chargeMoves =
[
	{
		"name": "Acid Spray",
		"type": "Poison",
		"pvpDamage": 20,
		"pvpEnergy": 50,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 20,
		"pveEnergy": 50,
		"pveCooldown": 3
	},
	{
		"name": "Aerial Ace",
		"type": "Flying",
		"pvpDamage": 55,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 55,
		"pveEnergy": 33,
		"pveCooldown": 2.4
	},
	{
		"name": "Air Cutter",
		"type": "Flying",
		"pvpDamage": 60,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.7
	},
	{
		"name": "Ancient Power",
		"type": "Rock",
		"pvpDamage": 45,
		"pvpEnergy": 45,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "ATK/DEF",
		"pvpEffectDelta": "+2",
		"pvpEffectTarget": "Self",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 3.5
	},
	{
		"name": "Ancient Power (Community Day)",
		"type": "Rock",
		"pvpDamage": 45,
		"pvpEnergy": 45,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "ATK/DEF",
		"pvpEffectDelta": "+2",
		"pvpEffectTarget": "Self",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 3.5
	},
	{
		"name": "Aqua Jet",
		"type": "Water",
		"pvpDamage": 45,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 2.6
	},
	{
		"name": "Aqua Tail",
		"type": "Water",
		"pvpDamage": 50,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Aura Sphere",
		"type": "Fighting",
		"pvpDamage": 100,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 1.8
	},
	{
		"name": "Aurora Beam",
		"type": "Ice",
		"pvpDamage": 80,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 3.55
	},
	{
		"name": "Avalanche",
		"type": "Ice",
		"pvpDamage": 90,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.7
	},
	{
		"name": "Blast Burn (Community Day)",
		"type": "Fire",
		"pvpDamage": 110,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 50,
		"pveCooldown": 3.3
	},
	{
		"name": "Blaze Kick",
		"type": "Fire",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 1.2
	},
	{
		"name": "Blizzard",
		"type": "Ice",
		"pvpDamage": 130,
		"pvpEnergy": 75,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 3.1
	},
	{
		"name": "Body Slam",
		"type": "Normal",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Body Slam (Community Day)",
		"type": "Normal",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Bone Club",
		"type": "Ground",
		"pvpDamage": 40,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Brave Bird",
		"type": "Flying",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 100,
		"pveCooldown": 2
	},
	{
		"name": "Brick Break",
		"type": "Fighting",
		"pvpDamage": 40,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Brine",
		"type": "Water",
		"pvpDamage": 60,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.3
	},
	{
		"name": "Bubble Beam",
		"type": "Water",
		"pvpDamage": 25,
		"pvpEnergy": 40,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Bug Buzz",
		"type": "Bug",
		"pvpDamage": 90,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 3.7
	},
	{
		"name": "Bulldoze",
		"type": "Ground",
		"pvpDamage": 80,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 3.5
	},
	{
		"name": "Close Combat",
		"type": "Fighting",
		"pvpDamage": 100,
		"pvpEnergy": 45,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Self",
		"pveDamage": 100,
		"pveEnergy": 100,
		"pveCooldown": 2.3
	},
	{
		"name": "Crabhammer",
		"type": "Water",
		"pvpDamage": 75,
		"pvpEnergy": 50,
		"pvpEffectChance": "12.50%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "+2",
		"pvpEffectTarget": "Self",
		"pveDamage": 85,
		"pveEnergy": 50,
		"pveCooldown": 1.9
	},
	{
		"name": "Cross Chop",
		"type": "Fighting",
		"pvpDamage": 50,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 50,
		"pveCooldown": 1.5
	},
	{
		"name": "Cross Poison",
		"type": "Poison",
		"pvpDamage": 40,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.5
	},
	{
		"name": "Crunch",
		"type": "Dark",
		"pvpDamage": 70,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 3.2
	},
	{
		"name": "Crush Claw",
		"type": "Normal",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 1.9
	},
	{
		"name": "Dark Pulse",
		"type": "Dark",
		"pvpDamage": 80,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 3
	},
	{
		"name": "Dazzling Gleam",
		"type": "Fairy",
		"pvpDamage": 110,
		"pvpEnergy": 70,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 3.5
	},
	{
		"name": "Dig",
		"type": "Ground",
		"pvpDamage": 100,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 4.7
	},
	{
		"name": "Disarming Voice",
		"type": "Fairy",
		"pvpDamage": 70,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 3.9
	},
	{
		"name": "Discharge",
		"type": "Electric",
		"pvpDamage": 65,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 65,
		"pveEnergy": 33,
		"pveCooldown": 2.5
	},
	{
		"name": "Doom Desire",
		"type": "Steel",
		"pvpDamage": 75,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 1.7
	},
	{
		"name": "Draco Meteor",
		"type": "Dragon",
		"pvpDamage": 150,
		"pvpEnergy": 65,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Self",
		"pveDamage": 150,
		"pveEnergy": 100,
		"pveCooldown": 3.6
	},
	{
		"name": "Draco Meteor (Community Day)",
		"type": "Dragon",
		"pvpDamage": 150,
		"pvpEnergy": 65,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Self",
		"pveDamage": 150,
		"pveEnergy": 100,
		"pveCooldown": 3.6
	},
	{
		"name": "Dragon Claw",
		"type": "Dragon",
		"pvpDamage": 50,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 1.7
	},
	{
		"name": "Dragon Pulse",
		"type": "Dragon",
		"pvpDamage": 90,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 3.6
	},
	{
		"name": "Dragon Pulse (Community Day)",
		"type": "Dragon",
		"pvpDamage": 90,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 3.6
	},
	{
		"name": "Drain Punch",
		"type": "Fighting",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 2.4
	},
	{
		"name": "Draining Kiss",
		"type": "Fairy",
		"pvpDamage": 60,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Drill Peck",
		"type": "Flying",
		"pvpDamage": 60,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 2.3
	},
	{
		"name": "Drill Run",
		"type": "Ground",
		"pvpDamage": 80,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.8
	},
	{
		"name": "Drill Run (Community Day)",
		"type": "Ground",
		"pvpDamage": 80,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.8
	},
	{
		"name": "Dynamic Punch",
		"type": "Fighting",
		"pvpDamage": 90,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.7
	},
	{
		"name": "Earth Power",
		"type": "Ground",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 3.6
	},
	{
		"name": "Earth Power (Community Day)",
		"type": "Ground",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 3.6
	},
	{
		"name": "Earthquake",
		"type": "Ground",
		"pvpDamage": 120,
		"pvpEnergy": 65,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 140,
		"pveEnergy": 100,
		"pveCooldown": 3.6
	},
	{
		"name": "Energy Ball",
		"type": "Grass",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 3.9
	},
	{
		"name": "Fell Stinger",
		"type": "Bug",
		"pvpDamage": 20,
		"pvpEnergy": 35,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "+1",
		"pvpEffectTarget": "Self",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.2
	},
	{
		"name": "Fire Blast",
		"type": "Fire",
		"pvpDamage": 140,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 140,
		"pveEnergy": 100,
		"pveCooldown": 4.2
	},
	{
		"name": "Fire Punch",
		"type": "Fire",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 55,
		"pveEnergy": 33,
		"pveCooldown": 2.2
	},
	{
		"name": "Fissure",
		"type": "Ground",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 2.8
	},
	{
		"name": "Flame Burst",
		"type": "Fire",
		"pvpDamage": 70,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Flame Charge",
		"type": "Fire",
		"pvpDamage": 70,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 3.8
	},
	{
		"name": "Flame Wheel",
		"type": "Fire",
		"pvpDamage": 60,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.7
	},
	{
		"name": "Flamethrower",
		"type": "Fire",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 2.2
	},
	{
		"name": "Flash Cannon",
		"type": "Steel",
		"pvpDamage": 110,
		"pvpEnergy": 65,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 100,
		"pveCooldown": 2.7
	},
	{
		"name": "Flying Press",
		"type": "Fighting",
		"pvpDamage": 90,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 50,
		"pveCooldown": 2.3
	},
	{
		"name": "Focus Blast",
		"type": "Fighting",
		"pvpDamage": 150,
		"pvpEnergy": 75,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 140,
		"pveEnergy": 100,
		"pveCooldown": 3.5
	},
	{
		"name": "Foul Play",
		"type": "Dark",
		"pvpDamage": 70,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 2
	},
	{
		"name": "Frenzy Plant (Community Day)",
		"type": "Grass",
		"pvpDamage": 100,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Frustration (Shadow)",
		"type": "Normal",
		"pvpDamage": 10,
		"pvpEnergy": 70,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 10,
		"pveEnergy": 33,
		"pveCooldown": 2
	},
	{
		"name": "Futuresight",
		"type": "Psychic",
		"pvpDamage": 120,
		"pvpEnergy": 65,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 120,
		"pveEnergy": 100,
		"pveCooldown": 2.7
	},
	{
		"name": "Giga Drain",
		"type": "Grass",
		"pvpDamage": 50,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 100,
		"pveCooldown": 3.9
	},
	{
		"name": "Giga Impact",
		"type": "Normal",
		"pvpDamage": 150,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 200,
		"pveEnergy": 100,
		"pveCooldown": 4.7
	},
	{
		"name": "Grass Knot",
		"type": "Grass",
		"pvpDamage": 90,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Gunk Shot",
		"type": "Poison",
		"pvpDamage": 130,
		"pvpEnergy": 75,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 3.1
	},
	{
		"name": "Gyro Ball",
		"type": "Steel",
		"pvpDamage": 80,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 3.3
	},
	{
		"name": "Heart Stamp",
		"type": "Psychic",
		"pvpDamage": 40,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Heat Wave",
		"type": "Fire",
		"pvpDamage": 95,
		"pvpEnergy": 75,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 95,
		"pveEnergy": 100,
		"pveCooldown": 3
	},
	{
		"name": "Heavy Slam",
		"type": "Steel",
		"pvpDamage": 70,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 2.1
	},
	{
		"name": "Horn Attack",
		"type": "Normal",
		"pvpDamage": 40,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.85
	},
	{
		"name": "Horn Drill",
		"type": "Normal",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 1.9
	},
	{
		"name": "Hurricane",
		"type": "Flying",
		"pvpDamage": 110,
		"pvpEnergy": 65,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 100,
		"pveCooldown": 2.7
	},
	{
		"name": "Hydro Cannon (Community Day)",
		"type": "Water",
		"pvpDamage": 80,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 1.9
	},
	{
		"name": "Hydro Pump",
		"type": "Water",
		"pvpDamage": 130,
		"pvpEnergy": 75,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 3.3
	},
	{
		"name": "Hydro Pump Blastoise",
		"type": "Water",
		"pvpDamage": 90,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 100,
		"pveCooldown": 4.5
	},
	{
		"name": "Hyper Beam",
		"type": "Normal",
		"pvpDamage": 150,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 150,
		"pveEnergy": 100,
		"pveCooldown": 3.8
	},
	{
		"name": "Hyper Fang",
		"type": "Normal",
		"pvpDamage": 80,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.5
	},
	{
		"name": "Ice Beam",
		"type": "Ice",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 3.3
	},
	{
		"name": "Ice Punch",
		"type": "Ice",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Icy Wind",
		"type": "Ice",
		"pvpDamage": 60,
		"pvpEnergy": 45,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 3.3
	},
	{
		"name": "Iron Head",
		"type": "Steel",
		"pvpDamage": 70,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 1.9
	},
	{
		"name": "Last Resort (Community Day)",
		"type": "Normal",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.9
	},
	{
		"name": "Leaf Blade",
		"type": "Grass",
		"pvpDamage": 70,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 2.4
	},
	{
		"name": "Leaf Tornado",
		"type": "Grass",
		"pvpDamage": 45,
		"pvpEnergy": 40,
		"pvpEffectChance": "50%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 3.1
	},
	{
		"name": "Leech Life",
		"type": "Bug",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 2.5
	},
	{
		"name": "Low Sweep",
		"type": "Fighting",
		"pvpDamage": 40,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Lunge",
		"type": "Bug",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 2.9
	},
	{
		"name": "Magnet Bomb",
		"type": "Steel",
		"pvpDamage": 70,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 2.8
	},
	{
		"name": "Mega Drain",
		"type": "Grass",
		"pvpDamage": 25,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 25,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Megahorn",
		"type": "Bug",
		"pvpDamage": 100,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 100,
		"pveCooldown": 2.2
	},
	{
		"name": "Meteor Mash",
		"type": "Steel",
		"pvpDamage": 100,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Meteor Mash (Community Day)",
		"type": "Steel",
		"pvpDamage": 100,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Mirror Coat",
		"type": "Psychic",
		"pvpDamage": 60,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Mirror Shot",
		"type": "Steel",
		"pvpDamage": 35,
		"pvpEnergy": 35,
		"pvpEffectChance": "30%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.4
	},
	{
		"name": "Moonblast",
		"type": "Fairy",
		"pvpDamage": 110,
		"pvpEnergy": 60,
		"pvpEffectChance": "30%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 3.9
	},
	{
		"name": "Mud Bomb",
		"type": "Ground",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 55,
		"pveEnergy": 33,
		"pveCooldown": 2.3
	},
	{
		"name": "Muddy Water",
		"type": "Water",
		"pvpDamage": 35,
		"pvpEnergy": 35,
		"pvpEffectChance": "30%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.2
	},
	{
		"name": "Night Shade",
		"type": "Ghost",
		"pvpDamage": 60,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Night Slash",
		"type": "Dark",
		"pvpDamage": 50,
		"pvpEnergy": 35,
		"pvpEffectChance": "12.50%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "+2",
		"pvpEffectTarget": "Self",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.2
	},
	{
		"name": "Octazooka",
		"type": "Water",
		"pvpDamage": 50,
		"pvpEnergy": 50,
		"pvpEffectChance": "50%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 50,
		"pveEnergy": 50,
		"pveCooldown": 2.3
	},
	{
		"name": "Ominous Wind",
		"type": "Ghost",
		"pvpDamage": 45,
		"pvpEnergy": 45,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "ATK/DEF",
		"pvpEffectDelta": "+2",
		"pvpEffectTarget": "Self",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.3
	},
	{
		"name": "Origin Pulse",
		"type": "Water",
		"pvpDamage": 130,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 1.7
	},
	{
		"name": "Outrage",
		"type": "Dragon",
		"pvpDamage": 110,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 50,
		"pveCooldown": 3.9
	},
	{
		"name": "Outrage (Community Day)",
		"type": "Dragon",
		"pvpDamage": 110,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 50,
		"pveCooldown": 3.9
	},
	{
		"name": "Overheat",
		"type": "Fire",
		"pvpDamage": 130,
		"pvpEnergy": 55,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Self",
		"pveDamage": 160,
		"pveEnergy": 100,
		"pveCooldown": 4
	},
	{
		"name": "Parabolic Charge",
		"type": "Electric",
		"pvpDamage": 25,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 25,
		"pveEnergy": 50,
		"pveCooldown": 2.8
	},
	{
		"name": "Petal Blizzard",
		"type": "Grass",
		"pvpDamage": 110,
		"pvpEnergy": 65,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 100,
		"pveCooldown": 2.6
	},
	{
		"name": "Play Rough",
		"type": "Fairy",
		"pvpDamage": 90,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.9
	},
	{
		"name": "Poison Fang",
		"type": "Poison",
		"pvpDamage": 40,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 35,
		"pveEnergy": 33,
		"pveCooldown": 1.7
	},
	{
		"name": "Power Gem",
		"type": "Rock",
		"pvpDamage": 80,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.9
	},
	{
		"name": "Power Whip",
		"type": "Grass",
		"pvpDamage": 90,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Power-Up Punch",
		"type": "Fighting",
		"pvpDamage": 20,
		"pvpEnergy": 35,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "+1",
		"pvpEffectTarget": "Self",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2
	},
	{
		"name": "Precipice Blades",
		"type": "Ground",
		"pvpDamage": 130,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 1.7
	},
	{
		"name": "Psybeam",
		"type": "Psychic",
		"pvpDamage": 70,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 3.2
	},
	{
		"name": "Psychic",
		"type": "Psychic",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.8
	},
	{
		"name": "Psycho Boost",
		"type": "Psychic",
		"pvpDamage": 70,
		"pvpEnergy": 35,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Self",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 4
	},
	{
		"name": "Psyshock",
		"type": "Psychic",
		"pvpDamage": 70,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 65,
		"pveEnergy": 33,
		"pveCooldown": 2.7
	},
	{
		"name": "Psystrike",
		"type": "Psychic",
		"pvpDamage": 90,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.3
	},
	{
		"name": "Razor Shell",
		"type": "Water",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 1.3
	},
	{
		"name": "Rest",
		"type": "Normal",
		"pvpDamage": 50,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Return (Shadow)",
		"type": "Normal",
		"pvpDamage": 130,
		"pvpEnergy": 70,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 35,
		"pveEnergy": 33,
		"pveCooldown": 0.7
	},
	{
		"name": "Rock Blast",
		"type": "Rock",
		"pvpDamage": 50,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.1
	},
	{
		"name": "Rock Slide",
		"type": "Rock",
		"pvpDamage": 80,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.7
	},
	{
		"name": "Rock Tomb",
		"type": "Rock",
		"pvpDamage": 70,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 3.2
	},
	{
		"name": "Rock Wrecker (Community Day)",
		"type": "Rock",
		"pvpDamage": 110,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 50,
		"pveCooldown": 3.6
	},
	{
		"name": "Sacred Sword",
		"type": "Fighting",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 55,
		"pveEnergy": 33,
		"pveCooldown": 1.2
	},
	{
		"name": "Sand Tomb",
		"type": "Ground",
		"pvpDamage": 25,
		"pvpEnergy": 40,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Opponent",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 4
	},
	{
		"name": "Scald",
		"type": "Water",
		"pvpDamage": 80,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 3.7
	},
	{
		"name": "Scald Blastoise",
		"type": "Water",
		"pvpDamage": 50,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 100,
		"pveCooldown": 4.7
	},
	{
		"name": "Seed Bomb",
		"type": "Grass",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 55,
		"pveEnergy": 33,
		"pveCooldown": 2.1
	},
	{
		"name": "Shadow Ball",
		"type": "Ghost",
		"pvpDamage": 100,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 50,
		"pveCooldown": 3
	},
	{
		"name": "Shadow Bone",
		"type": "Ghost",
		"pvpDamage": 0,
		"pvpEnergy": 0,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 0,
		"pveEnergy": 0,
		"pveCooldown": 2.8
	},
	{
		"name": "Shadow Punch",
		"type": "Ghost",
		"pvpDamage": 40,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 40,
		"pveEnergy": 33,
		"pveCooldown": 1.7
	},
	{
		"name": "Shadow Sneak",
		"type": "Ghost",
		"pvpDamage": 50,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.9
	},
	{
		"name": "Signal Beam",
		"type": "Bug",
		"pvpDamage": 75,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 75,
		"pveEnergy": 50,
		"pveCooldown": 2.9
	},
	{
		"name": "Silver Wind",
		"type": "Bug",
		"pvpDamage": 45,
		"pvpEnergy": 45,
		"pvpEffectChance": "10%",
		"pvpEffectStat": "ATK/DEF",
		"pvpEffectDelta": "+2",
		"pvpEffectTarget": "Self",
		"pveDamage": 70,
		"pveEnergy": 33,
		"pveCooldown": 3.7
	},
	{
		"name": "Skull Bash",
		"type": "Normal",
		"pvpDamage": 130,
		"pvpEnergy": 75,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "+1",
		"pvpEffectTarget": "Self",
		"pveDamage": 130,
		"pveEnergy": 100,
		"pveCooldown": 3.1
	},
	{
		"name": "Sky Attack",
		"type": "Flying",
		"pvpDamage": 80,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2
	},
	{
		"name": "Sludge",
		"type": "Poison",
		"pvpDamage": 50,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 50,
		"pveEnergy": 33,
		"pveCooldown": 2.1
	},
	{
		"name": "Sludge Bomb",
		"type": "Poison",
		"pvpDamage": 80,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.3
	},
	{
		"name": "Sludge Wave",
		"type": "Poison",
		"pvpDamage": 110,
		"pvpEnergy": 65,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 110,
		"pveEnergy": 100,
		"pveCooldown": 3.2
	},
	{
		"name": "Solar Beam",
		"type": "Grass",
		"pvpDamage": 150,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 180,
		"pveEnergy": 100,
		"pveCooldown": 4.9
	},
	{
		"name": "Stomp",
		"type": "Normal",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 55,
		"pveEnergy": 50,
		"pveCooldown": 1.7
	},
	{
		"name": "Stone Edge",
		"type": "Rock",
		"pvpDamage": 100,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 100,
		"pveCooldown": 2.3
	},
	{
		"name": "Struggle",
		"type": "Normal",
		"pvpDamage": 35,
		"pvpEnergy": 100,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 35,
		"pveEnergy": 0,
		"pveCooldown": 2.2
	},
	{
		"name": "Submission",
		"type": "Fighting",
		"pvpDamage": 60,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.2
	},
	{
		"name": "Super Power",
		"type": "Fighting",
		"pvpDamage": 85,
		"pvpEnergy": 40,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "ATK/DEF",
		"pvpEffectDelta": "-1",
		"pvpEffectTarget": "Self",
		"pveDamage": 85,
		"pveEnergy": 50,
		"pveCooldown": 3
	},
	{
		"name": "Surf",
		"type": "Water",
		"pvpDamage": 65,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 65,
		"pveEnergy": 50,
		"pveCooldown": 1.7
	},
	{
		"name": "Surf (Community Day)",
		"type": "Water",
		"pvpDamage": 65,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 65,
		"pveEnergy": 50,
		"pveCooldown": 1.7
	},
	{
		"name": "Swift",
		"type": "Normal",
		"pvpDamage": 60,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 50,
		"pveCooldown": 2.8
	},
	{
		"name": "Synchronoise",
		"type": "Psychic",
		"pvpDamage": 80,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Synchronoise (Community Day)",
		"type": "Psychic",
		"pvpDamage": 80,
		"pvpEnergy": 50,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Thunder",
		"type": "Electric",
		"pvpDamage": 100,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 100,
		"pveEnergy": 100,
		"pveCooldown": 2.4
	},
	{
		"name": "Thunder Punch",
		"type": "Electric",
		"pvpDamage": 55,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 1.8
	},
	{
		"name": "Thunderbolt",
		"type": "Electric",
		"pvpDamage": 90,
		"pvpEnergy": 55,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 80,
		"pveEnergy": 50,
		"pveCooldown": 2.5
	},
	{
		"name": "Twister",
		"type": "Dragon",
		"pvpDamage": 45,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 2.8
	},
	{
		"name": "Vice Grip",
		"type": "Normal",
		"pvpDamage": 40,
		"pvpEnergy": 40,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 35,
		"pveEnergy": 33,
		"pveCooldown": 1.9
	},
	{
		"name": "Water Pulse",
		"type": "Water",
		"pvpDamage": 70,
		"pvpEnergy": 60,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 70,
		"pveEnergy": 50,
		"pveCooldown": 3.2
	},
	{
		"name": "Weather Ball",
		"type": "Normal",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Weather Ball Fire",
		"type": "Fire",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Weather Ball Ice",
		"type": "Ice",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Weather Ball Water",
		"type": "Water",
		"pvpDamage": 60,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Wild Charge",
		"type": "Electric",
		"pvpDamage": 100,
		"pvpEnergy": 45,
		"pvpEffectChance": "100%",
		"pvpEffectStat": "DEF",
		"pvpEffectDelta": "-2",
		"pvpEffectTarget": "Self",
		"pveDamage": 90,
		"pveEnergy": 50,
		"pveCooldown": 2.6
	},
	{
		"name": "Wrap",
		"type": "Normal",
		"pvpDamage": 60,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 60,
		"pveEnergy": 33,
		"pveCooldown": 2.9
	},
	{
		"name": "Wrap Green",
		"type": "Normal",
		"pvpDamage": 25,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 25,
		"pveEnergy": 33,
		"pveCooldown": 2.9
	},
	{
		"name": "Wrap Pink",
		"type": "Normal",
		"pvpDamage": 25,
		"pvpEnergy": 45,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 25,
		"pveEnergy": 33,
		"pveCooldown": 2.9
	},
	{
		"name": "X-Scissor",
		"type": "Bug",
		"pvpDamage": 45,
		"pvpEnergy": 35,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 45,
		"pveEnergy": 33,
		"pveCooldown": 1.6
	},
	{
		"name": "Zap Cannon",
		"type": "Electric",
		"pvpDamage": 150,
		"pvpEnergy": 80,
		"pvpEffectChance": "N/A",
		"pvpEffectStat": "N/A",
		"pvpEffectDelta": "N/A",
		"pvpEffectTarget": "N/A",
		"pveDamage": 140,
		"pveEnergy": 100,
		"pveCooldown": 3.7
	}
];

var chargeMovesMap = {};
chargeMoves.forEach(
    function(move) {
        let name = move.name;
        chargeMovesMap[name] = move;
    }
);